version: '3.8'

services:
  f5-tts:
    build: .
    container_name: f5-tts-infer
    volumes:
      - ./output:/app/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]